[workspace]
members = [
  "lib-dispatch",
  "lib-log",
  "lib-sqlite",
  "flowy-net",
  "flowy-sdk",
  "dart-ffi",
  "flowy-user",
  "flowy-test",
  "flowy-database",
  "flowy-folder",
  "dart-notify",
  "flowy-block",
  "flowy-error",
  "flowy-sync",
  "flowy-grid",
]

[profile.dev]
split-debuginfo = "unpacked"
