[workspace]
members = [
  "lib-dispatch",
  "lib-log",
  "flowy-net",
  "flowy-sdk",
  "dart-ffi",
  "flowy-user",
  "flowy-test",
  "flowy-database",
  "flowy-core",
  "dart-notify",
  "flowy-document",
]

exclude = ["../backend"]

[profile.dev]
split-debuginfo = "unpacked"
