[tasks.rust_clean]
script = [
  """
    cd rust-lib
    cargo clean

    cd ../../shared-lib
    cargo clean

    rm -rf lib-infra/.cache
  """,
]
script_runner = "@shell"

[tasks.rust_clean.windows]
script = [
  """
    cd rust-lib
    cargo clean

    cd ../../shared-lib
    cargo clean

    rmdir /s/q "lib-infra/.cache"
  """,
]
script_runner = "@duckscript"