[tasks.rust_clean]
run_task = { name = ["cargo_clean","rm_macro_build_cache", "rm_generated_protobuf_files"] }

[tasks.cargo_clean]
script = [
  """
    cd rust-lib
    cargo clean -q

    cd ../../shared-lib
    cargo clean -q
  """,
]
script_runner = "@shell"


[tasks.rm_macro_build_cache]
script = [
  """
    path = canonicalize ../shared-lib/lib-infra/.cache
    if is_path_exists ${path}
      rm -rf ${path}
    end
  """,
]
script_runner = "@duckscript"


[tasks.rm_generated_protobuf_files]
script = [
  """

  """,
]
script_runner = "@duckscript"