[workspace]
members = [
  "flowy-user-infra",
  "flowy-core-infra",
  "flowy-collaboration",
  "lib-ot",
  "lib-ws",
  "lib-sqlite",
  "lib-infra",
  "backend-service",
  "flowy-derive",
  "flowy-ast",
]

[profile.dev]
split-debuginfo = "unpacked"
