[workspace]
members = [
  "flowy-user-data-model",
  "flowy-folder-data-model",
  "flowy-sync",
  "lib-ot",
  "lib-ws",
  "lib-infra",
  "flowy-derive",
  "flowy-ast",
  "flowy-error-code",
  "flowy-grid-data-model",
]

[profile.dev]
split-debuginfo = "unpacked"
