[package]
name = "lib-infra"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
log = "0.4.14"
chrono = "0.4.19"
bytes = { version = "1.0" }
pin-project = "1.0"
futures-core = { version = "0.3" }
tokio = { version = "1.0", features = ["time", "rt"] }
rand = "0.8.3"

cmd_lib = { version = "1", optional = true }
protoc-rust = { version = "2", optional = true }
walkdir = { version = "2", optional = true }

flowy-ast = { path = "../flowy-ast", optional = true}
similar = { version = "1.2.2", optional = true }
syn = { version = "1.0.60", features = ["extra-traits", "parsing", "derive", "full"], optional = true }
fancy-regex = { version = "0.5.0", optional = true }
lazy_static = { version = "1.4.0", optional = true }
tera = { version = "1.5.0", optional = true}
itertools = {versino = "0.10", optional = true}
phf = { version = "0.8.0", features = ["macros"], optional = true }
console = {version = "0.14.0", optional = true}
serde = { version = "1.0", features = ["derive"], optional = true}
toml = {version = "0.5.8", optional = true}

[features]
pb_gen = ["cmd_lib", "protoc-rust", "walkdir"]
proto_gen = [
    "flowy-ast",
    "similar",
    "syn",
    "fancy-regex",
    "lazy_static",
    "tera",
    "itertools",
    "phf",
    "walkdir",
    "console",
    "serde",
    "toml"
]
dart = []