
proto_crates = [
    "src/event_map.rs",
    "src/services/field/type_options",
    "src/services/field/field_entities.rs",
    "src/services/cell/cell_entities.rs",
    "src/services/row/row_entities.rs",
    "src/dart_notification.rs"
]
event_files = ["src/event_map.rs"]