# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DartLint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  CARGO_TERM_COLOR: always

jobs:  
  flutter-analyze:
    name: flutter analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Generate language files
        working-directory: frontend/app_flowy
        run:
          flutter pub get
          flutter pub run easy_localization:generate -S assets/translations/
          flutter pub run easy_localization:generate -f keys -o locale_keys.g.dart -S assets/translations -s en.json
      - name: flutter analyze
        working-directory: frontend/app_flowy
        run: flutter analyze

