name: Strings update
on:
  push:
    branches: main
    paths:
      - "frontend/app_flowy/assets/translations/en.json"
jobs:
  # some way to send notification
  - name: Notify in Discord
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    uses: Ilshidur/action-discord@master
    with:
      args: '@appflowytranslators English UI strings has been updated.'
