name: Release landed
on:
  release:
    types: [published]
jobs:
  - name: Notify in Discord
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    uses: Ilshidur/action-discord@master
    with:
      args: '${{ github.event.tag_name }} is out 🚀 ${{ github.event.url }}\n${{ github.event.body }}'