name: RustLint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        run: |
          curl \
            --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup toolchain install stable
          rustup default stable
      - name: Install protobuf tool
      - run:
          cargo install --force cargo-make
          cargo make flowy_dev
          echo PATH="$PATH":"$HOME/.pub-cache/bin" >> $GITHUB_PATH
        working-directory: frontend
      - name: Frontend tests
        working-directory: frontend/rust-lib
        run: cargo test
      - name: Shared-lib tests
        working-directory: shared-lib
        run: cargo test
